data(mtcars)
mtcars

# #feature explanations
# mpg: Fuel consumption (Miles per (US) gallon): more powerful and heavier cars tend to consume more fuel.
# cyl: Number of cylinders: more powerful cars often have more cylinders
# disp: Displacement (cu.in.): the combined volume of the engine's cylinders
# hp: Gross horsepower: this is a measure of the power generated by the car
# drat: Rear axle ratio: this describes how a turn of the drive shaft corresponds to a turn of the wheels. Higher values will decrease fuel efficiency.
# wt: Weight (1000 lbs): pretty self-explanatory!
# qsec: 1/4 mile time: the cars speed and acceleration
# vs: Engine block: this denotes whether the vehicle's engine is shaped like a "V", or is a more common straight shape.
# am: Transmission: this denotes whether the car's transmission is automatic (0) or manual (1).
# gear: Number of forward gears: sports cars tend to have more gears.
# carb: Number of carburetors: associated with more powerful engines

#creating PCA
mtcars.pca <- prcomp(mtcars[,c(1:7,10,11)], center = TRUE,scale. = TRUE)
summary(mtcars.pca)      #PC1 explains 63% total variabnce, PC2 explains 23% and so on
str(mtcars.pca)

#plotting PCA
library(devtools)
#install_github("vqv/ggbiplot") #just used blank line when asked question
library(ggbiplot)
ggbiplot(mtcars.pca) #basic plot
ggbiplot(mtcars.pca, labels=rownames(mtcars)) #puts name of car in question

#looking at origin country for cars
mtcars.country <- c(rep("Japan", 3), rep("US",4), rep("Europe", 7),rep("US",3), "Europe", rep("Japan", 3), rep("US",4), rep("Europe", 3), "US", rep("Europe", 3))
ggbiplot(mtcars.pca, ellipse=TRUE, labels=rownames(mtcars), groups=mtcars.country)

#scaling samples with obs.scale and var.scale
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,  labels=rownames(mtcars), groups=mtcars.country)

#removing arrows with var.axes
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,var.axes=FALSE,   labels=rownames(mtcars), groups=mtcars.country)

#Customization of ggbiplot (similar to ggplot)
  #Colors: scale_color_manual()
  #Title: ggtitle()
  #Theme: theme_minimal()
  #Legend: theme(legend.position = _____)
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,  labels=rownames(mtcars), groups=mtcars.country) +
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "dark blue"))+
  ggtitle("PCA of mtcars dataset")+
  theme_minimal()+
  theme(legend.position = "bottom")


#adding sample (outlier)
spacecar <- c(1000,60,50,500,0,0.5,2.5,0,1,0,0)

mtcarsplus <- rbind(mtcars, spacecar)
mtcars.countryplus <- c(mtcars.country, "Jupiter")

mtcarsplus.pca <- prcomp(mtcarsplus[,c(1:7,10,11)], center = TRUE,scale. = TRUE)

#plot does not take into account who skewed the results are from the one point
ggbiplot(mtcarsplus.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample added")+
  theme_minimal()+
  theme(legend.position = "bottom")


#Different sample that does not use spacecar to define PCs
  #Looking at how spacecar compares to PCA center (mtcars.pca$center)
s.sc <- scale(t(spacecar[c(1:7,10,11)]), center= mtcars.pca$center)
s.pred <- s.sc %*% mtcars.pca$rotation

mtcars.plusproj.pca <- mtcars.pca
mtcars.plusproj.pca$x <- rbind(mtcars.plusproj.pca$x, s.pred)

ggbiplot(mtcars.plusproj.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample projected")+
  theme_minimal()+
  theme(legend.position = "bottom")
