data(mtcars)
mtcars

# #feature explanations
# mpg: Fuel consumption (Miles per (US) gallon): more powerful and heavier cars tend to consume more fuel.
# cyl: Number of cylinders: more powerful cars often have more cylinders
# disp: Displacement (cu.in.): the combined volume of the engine's cylinders
# hp: Gross horsepower: this is a measure of the power generated by the car
# drat: Rear axle ratio: this describes how a turn of the drive shaft corresponds to a turn of the wheels. Higher values will decrease fuel efficiency.
# wt: Weight (1000 lbs): pretty self-explanatory!
# qsec: 1/4 mile time: the cars speed and acceleration
# vs: Engine block: this denotes whether the vehicle's engine is shaped like a "V", or is a more common straight shape.
# am: Transmission: this denotes whether the car's transmission is automatic (0) or manual (1).
# gear: Number of forward gears: sports cars tend to have more gears.
# carb: Number of carburetors: associated with more powerful engines

#creating PCA
mtcars.pca <- prcomp(mtcars[,c(1:7,10,11)], center = TRUE,scale. = TRUE)
summary(mtcars.pca)      #PC1 explains 63% total variabnce, PC2 explains 23% and so on
mtcars.pca
str(mtcars.pca)

mtcars.pca$sd^2 # This produces the explained variance
mtcars.pca$rotation # Vectors -- have a direction (+/-) and magnitude (range form -1 to 1)
mtcars.pca$x # "Scores" x/y coordinates = "eigenvalues"

mtcars.pca2 <- princomp(mtcars[,c(1:7,10,11)], center = TRUE,scale. = TRUE)
mtcars.pca2$loadings

mtcars.pca$scale

#plotting PCA
library(devtools)
# install_github("vqv/ggbiplot") #just used blank line when asked question
library(ggbiplot)
ggbiplot(mtcars.pca) #basic plot
ggbiplot(mtcars.pca, labels=rownames(mtcars)) #puts name of car in question

#looking at origin country for cars
mtcars.country <- c(rep("Japan", 3), rep("US",4), rep("Europe", 7),rep("US",3), "Europe", rep("Japan", 3), rep("US",4), rep("Europe", 3), "US", rep("Europe", 3))
ggbiplot(mtcars.pca, ellipse=TRUE, labels=rownames(mtcars), groups=mtcars.country)

#scaling samples with obs.scale and var.scale
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,  labels=rownames(mtcars), groups=mtcars.country)

#removing arrows with var.axes
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,var.axes=FALSE,   labels=rownames(mtcars), groups=mtcars.country)

#Customization of ggbiplot (similar to ggplot)
  #Colors: scale_color_manual()
  #Title: ggtitle()
  #Theme: theme_minimal()
  #Legend: theme(legend.position = _____)
ggbiplot(mtcars.pca,ellipse=TRUE,obs.scale = 1, var.scale = 1,  labels=rownames(mtcars), groups=mtcars.country) +
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "dark blue"))+
  ggtitle("PCA of mtcars dataset")+
  theme_minimal()+
  theme(legend.position = "bottom")


#adding sample (outlier)
spacecar <- c(1000,60,50,500,0,0.5,2.5,0,1,0,0)

mtcarsplus <- rbind(mtcars, spacecar)
mtcars.countryplus <- c(mtcars.country, "Jupiter")

mtcarsplus.pca <- prcomp(mtcarsplus[,c(1:7,10,11)], center = TRUE,scale. = TRUE)

#plot does not take into account who skewed the results are from the one point
ggbiplot(mtcarsplus.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample added")+
  theme_minimal()+
  theme(legend.position = "bottom")


#Different sample that does not use spacecar to define PCs
  #Looking at how spacecar compares to PCA center (mtcars.pca$center)
s.sc <- scale(t(spacecar[c(1:7,10,11)]), center= mtcars.pca$center)
s.pred <- s.sc %*% mtcars.pca$rotation

mtcars.plusproj.pca <- mtcars.pca
mtcars.plusproj.pca$x <- rbind(mtcars.plusproj.pca$x, s.pred)

ggbiplot(mtcars.plusproj.pca, obs.scale = 1, var.scale = 1, ellipse = TRUE, circle = FALSE, var.axes=TRUE, labels=c(rownames(mtcars), "spacecar"), groups=mtcars.countryplus)+
  scale_colour_manual(name="Origin", values= c("forest green", "red3", "violet", "dark blue"))+
  ggtitle("PCA of mtcars dataset, with extra sample projected")+
  theme_minimal()+
  theme(legend.position = "bottom")




#beginning to implement techniques from mtcars into phenological data
#loading in packages used in soil graphs script
library(devtools)
# install_github("vqv/ggbiplot") #just used blank line when asked question
library(ggbiplot)
library("dplyr"); library("plyr"); library("readr")
library(ggplot2)
library(rgdal); library(sp); library(raster)
library(Hmisc)
library(data.table)

#Malus Collection with Morton Arb Data Point
path.dat <- "D:/Data_IMLS_Ecological_Value/Soil_Extract_Drive/Soil_Extract"  
  #if data is on hard drive
#path.dat <- "/Volumes/GoogleDrive/Shared drives/IMLS MFA/Environmental Niche Value/Extracted Data/Soil_Extract/" 
  #if data is from shared google folder
malus_soil <- list.files(path = path.dat,
                         pattern = "Malus", full.names = TRUE)
soilcols <- names(read.csv(malus_soil[1]))
col.char <- which(soilcols %in% c("nativeDatabaseID", "MU.SOURCE1"))
coltype <- rep(NA, length(soilcols))
coltype[col.char] <- "character"
malus_all <-  lapply(malus_soil, read.csv, colClasses=coltype) %>% bind_rows()
MortonArb_Data <- read.csv(file.path(path.dat,"0_MortonArb.csv"))
malus_all <- rbind.fill(malus_all, MortonArb_Data)
head(malus_all)
tail(malus_all)

#Quercus Collection with Morton Arb Data Point
quercus_soil <- list.files(path = path.dat,
                           pattern = "Quercus", full.names = TRUE)
soilcols <- names(read.csv(quercus_soil[1]))
col.char <- which(soilcols %in% c("nativeDatabaseID", "MU.SOURCE1"))
coltype <- rep(NA, length(soilcols))
coltype[col.char] <- "character"
quercus_all <-  lapply(quercus_soil, read.csv, colClasses=coltype) %>% bind_rows()
quercus_all <- rbind.fill(quercus_all, MortonArb_Data)
head(quercus_all)
tail(quercus_all)

#Tilia Collection with Morton Arb Data Point
tilia_soil <- list.files(path = path.dat,
                         pattern = "Tilia", full.names = TRUE)
soilcols <- names(read.csv(tilia_soil[1]))
col.char <- which(soilcols %in% c("nativeDatabaseID", "MU.SOURCE1"))
coltype <- rep(NA, length(soilcols))
coltype[col.char] <- "character"
tilia_all <-  lapply(tilia_soil, read.csv, colClasses=coltype) %>% bind_rows()
tilia_all <- rbind.fill(tilia_all, MortonArb_Data)
head(tilia_all)
tail(tilia_all)

#Ulmus Collection with Morton Arb Data Point
ulmus_soil <- list.files(path = path.dat,
                         pattern = "Ulmus", full.names = TRUE)
soilcols <- names(read.csv(ulmus_soil[1]))
col.char <- which(soilcols %in% c("nativeDatabaseID", "MU.SOURCE1"))
coltype <- rep(NA, length(soilcols))
coltype[col.char] <- "character"
ulmus_all <-  lapply(ulmus_soil, read.csv, colClasses=coltype) %>% bind_rows()
ulmus_all <- rbind.fill(ulmus_all, MortonArb_Data)
head(ulmus_all)
tail(ulmus_all)



#creating the PCA Plots for the Genera: considered the definite & potential characteristics from Work Plan
#choosing only the important traits: only looked at topsoil
#had no categorical variables: REF.DEPTH, T.USDA.TEX.CLASS
important_traits <- c("T.GRAVEL", "T.SAND", "T.SILT", "T.CLAY", "T.OC", "T.PH.H2O", 
                      "T.TEB", "T.ECE", "AWC_VALUE", "T.REF.BULK.DENSITY", "T.TEXTURE", 
                      "ROOTS", "T.CEC.CLAY", "T.CEC.SOIL", "T.CACO3", "T.CASO4", "T.ESP")


#getting rid of the malus NA values
malus_all <- malus_all[complete.cases(malus_all[,important_traits]),]
#Malus PCA
malus.pca <- prcomp(malus_all[,important_traits], center = TRUE,scale. = TRUE) 
  #error with missing/infinite values: I think I need to get rid of the NAs or convert each column into a numeric
summary(malus.pca)
malus.pca$rotation

#getting rid of the quercus NA values
quercus_all <- quercus_all[complete.cases(quercus_all[,important_traits]),]
#Quercus PCA
quercus.pca <- prcomp(quercus_all[,c(important_traits)], center = TRUE,scale. = TRUE)
summary(quercus.pca)
quercus.pca$rotation

#getting rid of the tilia NA values
tilia_all <- tilia_all[complete.cases(tilia_all[,important_traits]),]
#Tilia PCA
tilia.pca <- prcomp(tilia_all[,c(important_traits)], center = TRUE,scale. = TRUE)
summary(tilia.pca)
tilia.pca$rotation

#getting rid of the ulmus NA values
ulmus_all <- ulmus_all[complete.cases(ulmus_all[,important_traits]),]
#Ulmus PCA
ulmus.pca <- prcomp(ulmus_all[,c(important_traits)], center = TRUE,scale. = TRUE)
summary(ulmus.pca)
ulmus.pca$rotation